### ISSUE TITLE
Accessing metadata (GDALMayorObject)

### ISSUE THREAD

**Issue by jdroenner** [georust/rust-gdal#20]
`GDALMayorObject` is the base class for everything in GDAL: `GDALDataset`, `GDALRasterBand`and `OGRLayer`. Also since GDAL 2.0 the separation between raster and vector datasets was removed. Every dataset is now a `GDALDataset` (`OGRDataSource` is deprecated).

[GDALMayorObject ](http://www.gdal.org/classGDALMajorObject.html) provides methods to access metadata e.g. `GetMetadataItem`. Sadly there is no way to access metadata from rust-gdal.

My current idea to provide access to metadata for all `GDALMayorObject` based types is the following:
- Add a (non exported)  trait to access the c-pointer:

```
trait MajorObject {
    unsafe fn get_gdal_object_ptr(&self) -> *const c_void;
}
```
- Add a trait with default implementations (using the pointer) to access the metadata:

```
pub trait Metadata: MajorObject {
    fn get_metadata_item(&self, key: &str, domain: &str) -> Option<String> { ... }
    ...
}
```
- Implement MajorObject and Metadata for all matching types:

```
pub struct Dataset {
    c_dataset: *const c_void,
}

impl MajorObject for Dataset {
    unsafe fn get_gdal_object_ptr(&self) -> *const c_void {
        self.c_dataset
    }
}

impl Metadata for Dataset {}
```

I have a working implementation of this approach, but I would like to hear other ideas :)

**Comment by frewsxcv** [comment]
This sounds great! Would love to see some metadata retrieval implemented for all the types. I can't think of any better ideas at the time for how to structure this, so feel free to open a PR for your changes. If we think of something better, we can always release a new version :)
