### ISSUE TITLE
split into gdal-sys and gdal crate

### ISSUE THREAD

**Issue by jdroenner** [georust/rust-gdal#25]
Split rust-gdal into a gdal-sys and a (rust-) gdal crate.

(I'm currently working on this)

**Comment by frewsxcv** [comment]
Sounds great! I've been meaning to do this for a while.

**Comment by jdroenner** [comment]
@frewsxcv should i add the rust-sys repository to georust? ;)

**Comment by frewsxcv** [comment]
I'd recommend having both `gdal` and `gdal-sys` library crates exist within the same repository. This way, if there are ever updates to `gdal-sys`, `gdal` will get updated to reflect the changes at the same time.

There a couple strategies for doing this:

### `gdal-sys` within `gdal`

```
/Cargo.toml (config for 'gdal')
/src/ (source files for 'gdal')
/gdal-sys/ (crate for 'gdal-sys')
/gdal-sys/Cargo.toml (config for 'gdal-sys')
/gdal-sys/src/ (source files for 'gdal-sys')
```

An example: https://github.com/alexcrichton/git2-rs

### `gdal-sys` and `gdal` separate w/ cargo workspace

cargo workspaces are relatively new: https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md

```
/Cargo.toml (workspace config)
/gdal/ (crate for 'gdal')
/gdal/Cargo.toml (config for 'gdal')
/gdal/src/ (source files for 'gdal')
/gdal-sys/ (crate for 'gdal-sys')
/gdal-sys/Cargo.toml (config for 'gdal-sys')
/gdal-sys/src/ (source files for 'gdal-sys')
```

An example: https://github.com/servo/webrender

----------

Nowadays I prefer the second option

**Comment by jdroenner** [comment]
I've been wondering how to do this and the examples are really helpful, thanks! Cargo workspaces look really nice.
