### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-gdal#3]
https://crates.io/search?q=gdal

**Comment by frewsxcv** [comment]
I pushed this to crates.io https://crates.io/crates/gdal

If anyone wants access, you'll need an account there. Currently the site doesn't support automatic GitHub organization access, so I have to add you individually

/cc @mgax

**Comment by frewsxcv** [comment]
@mgax I tried to add you, but it looks like you don't have an account there

**Comment by mgax** [comment]
@frewsxcv I've created an account. Thanks for pushing this.
