### ISSUE TITLE
Switch from 'geo' to 'geo-types'

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-gdal#59]
https://github.com/georust/rust-geo/pull/201

**Comment by jdroenner** [comment]
Great work @lnicola :)
I think we should also replace the `ToGeo` trait with `TryInto` (https://github.com/georust/rust-geo/issues/212). 
This way we should be able to remove the dependency on the geo crate.

**Comment by lnicola** [comment]
Something like the new commit, then?

I used `from` instead of `into` in the test because for some reason it wasn't able to deduce the type. `TryFrom` is still unstable, unfortunately.

**Comment by jdroenner** [comment]
Great :) I guess we can add a TryFrom version when it gets stable again...
