### ISSUE TITLE
Consider making a new release

### ISSUE THREAD

**Issue by lnicola** [georust/rust-gdal#61]
There's been a couple of changes lately: `bindgen` for `gdal-sys`, `failure` support and, to a lesser extent, moving to `geo-types`. It might be worth issuing new releases for these.

**Comment by jdroenner** [comment]
Will try to do this today. Can we replace the bindgen git dependency with a release?

**Comment by lnicola** [comment]
Ah, sorry, I forgot about that dependency :-(. Maybe I'll make a PR for it (I'm a bit worried about differences in the generated code).

This can be closed, I guess. Thanks.

**Comment by lnicola** [comment]
Actually, that might be https://github.com/rust-lang-nursery/rust-bindgen/issues/1265
